name: note_gm
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.0
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.3.3
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  http: ^0.13.1
  image_picker: ^0.8.5+3
  path_provider: ^2.1.2
  font_awesome_flutter: ^10.8.0
  google_mlkit_face_detection: ^0.12.0
  google_ml_kit: ^0.19.0
  aws_signature_v4: ^0.6.3
  aws_s3_api: ^2.0.0
  aws_sdk: ^0.0.3
  aws_rekognition_api: ^2.0.0
  aws_dynamodb_api: ^2.0.0
  flutter_dotenv: ^5.2.1
  mask_text_input_formatter: ^2.9.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/illustrations/find.png
    - assets/illustrations/reconhecimento-facial.png     

